### ISSUE TITLE
Rakenduse kood eraldi projekti

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#1]
Teen ettepaneku tõsta rakenduse riigiteenused.ee kood selguse ja hallatavuse parandamiseks muust materjalist eraldi projekti.

**Comment by tormi** [comment]
Juba lisatud registri kohta tehtud kannetele tuleks lisada vastav registrile viitav label.

**Comment by tormi** [comment]
Vaatasin veidi täpsemalt - hetkel on avaldatud vaid koodi dokumentatsioon.

**Comment by RRisto** [comment]
Mis dokumentatsiooni veel peaks avaldama? Mis lisatud registritest jutt käib?

**Comment by tormi** [comment]
Aadressil https://github.com/MKM-ITAO/riigiteenused/tree/master/Rakenduse%20kood/Riigiteenused%20code%20documentation oled avaldanud mitte riigiteenused.ee koodi, vaid riigiteenused.ee API dokumentatsiooni. Tegin viimase nähtavaks siin: http://tormi.github.io/riigiteenused/ ([kood](https://github.com/tormi/riigiteenused/tree/gh-pages)).

Drupali riigiteenused.ee koodi hetkel avaldatud ei ole, selle suhtes olen siin projektis ja sooviksin edaspidi eraldi koodiprojektis kandeid teha.

**Comment by tormi** [comment]
Kood on avaldatud projektis https://github.com/MKM-ITAO/riigiteenused_kood
