### ISSUE TITLE
Teenusekaardile ei ole võimalik viidata

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#10]
Teenusekaardil puudub aadress (URL), seetõttu saab teenusele hetkel viidata ainult [otsingutulemusena](https://www.mkm.ee/et/teenuste-otsing?title-search=Teenuste+kataloog&field_t_kirjeldus_value=&sort_by=field_t_osutatud_teenuste_arv_value). Ettepanek lisada igale teenusele oma (P)URL kasutades elementi "identifikaator", näiteks https://www.riigiteenused.ee/teenus/TJA-007. Väga lihtne ka administraatori tasemel lisada kasutades moodulit [pathauto](https://www.drupal.org/project/pathauto).

Lisaks, hetkel on teenuse nimetuse (pildil kollase ringi sees) taha haagitud e-teenuse osutamise aadress. Teen ettepaneku see kaardil eraldi URL-ina esitada ja nimetuse URL-ina kasutada teenusekaardi URL-i.

![teenuse url](https://cloud.githubusercontent.com/assets/146800/10477672/c31cf6a6-7260-11e5-8821-ee921d9c7598.PNG)

**Comment by RRisto** [comment]
võtame arvesse ning järgmine iteratsioon saab seda parandada.

**Comment by RRisto** [comment]
verisoonis 2 funktisonaalsus olemas
