### ISSUE TITLE
Teenuse identifikaatorit ei ole võimalik kasutada otsingutingimusena

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#11]
Teenuse identifikaatorit ei ole võimalik kasutada otsingutingimusena. Seotud kandega #10.

**Comment by RRisto** [comment]
võtame arvesse ning järgmine iteratsioon saab seda parandada.

**Comment by tormi** [comment]
Aitäh! Äkki kasutaks sellisteks märkusteks [GitHub milestones](https://help.github.com/articles/creating-and-editing-milestones-for-issues-and-pull-requests/) funktsionaalsust?

**Comment by RRisto** [comment]
jep, võtsin kasutusele

**Comment by tormi** [comment]
:+1:

**Comment by RRisto** [comment]
versiooni 2 seda ei lisanud, kuna praegustel kataloogi kasutajate poolt seda tellimus tulnud. lisasime teenuste filtreerimiseks lisafiltreid
