### ISSUE TITLE
RIA: Lisada sihtgrupi klassifikaatorisse "Asutus"

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#16]
Lisada sihtgrupi klassifikaatorisse lisaks "Kodanikule", "Ettevõtjale" ja "Ametnikule" ka "Asutus". See peaks aitama eristama, kas teenust saab tarbida ametnik või teenistuja. Samas võib tekitada segadust kasutajates, kuna pole üheselt mõistetav, milline teenus on suunatud ametnikule ja milline asutusele.

**Comment by tormi** [comment]
> peaks aitama eristama, kas teenust saab tarbida ametnik või teenistuja

Kas RIA avas, miks selline detailsus vajalik on? Ka kodanikku on võimalik liigitada a'la _beebi, mudilane, laps, teismeline, noor, täiskasvanu ja vanur_ ;)

Ehk tuleks kaaluda teenuste jaotamist hoopis avalikeks teenusteks rohelise raamatu mõistes ja siseteenusteks (vajalikud selleks, et avalikke teenuseid saaks osutada)?

**Comment by RRisto** [comment]
Eks siin tuleb leida tasakaal meie sisemiste jaotuste ja kliendile arusaadavuse vahel. Vaatame ehk tuleb selle kohta ka teistelt tagasisidet.

**Comment by tormi** [comment]
> teistelt tagasisidet

See oli infotunnis eraldi teema, et kuhu tagasisidet anda. Võimalik, et peaks Github'i keskkonna koolitustes/juhendites (rohkem) pilti tooma.

**Comment by RRisto** [comment]
Oleme seda koolitustel teinud.

**Comment by tormi** [comment]
:+1:

**Comment by RRisto** [comment]
versioonis 2 lisasime lõplikult kokku lepitud klassifikaatori
