### ISSUE TITLE
ITAO: linnuke hädaolukorra seaduse, riigikaitse strateegiaga seotud teenustele

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#19]
Teenuse juurde peaks olema võimalik ära märkida, kas teenus on seotud hädaolukorra seaduse või riigikaitse strateegiaga.

**Comment by tormi** [comment]
Ma pigem lisaks taksonoomia abil üldisema portfellihalduse võimekuse, loetletud nimekiri ei jää kindlasti lõplikuks.

**Comment by RRisto** [comment]
versioonis 2 olemas
