### ISSUE TITLE
Versioneerimine vaikimisi sisse

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#2]
Teen ettepaneku lülitada [teenuse lisamisel](https://www.riigiteenused.ee/et/node/add/teenus) versioneerimine vaikimisi sisse, et teenusekaardi muudatuste ajalugu tekiks automaatselt.

![versioneerimine sisse](https://cloud.githubusercontent.com/assets/146800/10426335/fcaace2c-70e7-11e5-8a44-14209ea403b5.PNG)

**Comment by RRisto** [comment]
Hetkel oleme meelega redaktsioonide haldamise välja jätnud lihtsuse tagamiseks. Kui suudame saavutada enam-vähem ühtlase taseme teenuste kirjeldamisel, siis saame paika panna kuidas redaktsioone hallata.

**Comment by tormi** [comment]
Redaktsioone ei olegi vaja hallata juhul, kui versioneerimine vaikimisi sisse lülitada. Kui lisada [diff moodul](https://www.drupal.org/project/diff), tekib vastava õigustega isikule ka hea haldamise töövahend.

> This module adds a tab for sufficiently permissioned users. The tab shows all revisions like standard Drupal but it also allows pretty viewing of all added/changed/deleted words between revisions.

Vt näiteks https://www.drupal.org/node/20492/revisions/view/2520178/2520180

**Comment by RRisto** [comment]
versioonis 2 olemas
