### ISSUE TITLE
RIHA-s kirjeldatud teenuste importimine

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#21]
Teen ettepaneku enne andmekorje algust importida RIHA-st olemasolevad teenused koos teenuse osutamise kanaliga. Lisaks tuleks kiirelt kokku leppida, kas teenuste üle peetakse edaspidi arvestust nii riigiteenused.ee's kui RIHA's või paneme viimase teenuste osa kinni. Kahes kohas pidamine läheb mh vastuollu [AvTS](https://www.riigiteataja.ee/akt/avts#para43b6)-iga :)

**Update**: Lisaks [RIHA](https://riha.eesti.ee/)'le on seni andmeteenuseid kirjeldatud ka avaandmete portaalis [opendata.riik.ee](https://opendata.riik.ee/).

Seotud: #6, #18

**Comment by tormi** [comment]
Lisaks tuleks kiirelt kokku leppida, kas teenuste üle peetakse edaspidi arvestust nii riigiteenused.ee's kui RIHA's või paneme viimase teenuste osa kinni. Kahes kohas pidamine läheb mh vastuollu AvTS-iga :)

**Comment by tormi** [comment]
### KVR e-teenused\* RIHA-s

![riha_kvr](https://cloud.githubusercontent.com/assets/146800/10606388/2ebdcd5c-773b-11e5-93ff-0f043b117039.PNG)
![riha_kvr_teenused](https://cloud.githubusercontent.com/assets/146800/10606392/33e592a6-773b-11e5-8138-0fa82ca10824.PNG)
*- Tuleb tunnistada, et kirjeldused vajavad uuendamist;)

Valitsemisala x-tee teenuste konsolideerimise tõttu _wiki_-nimelise toru alla kajastatakse KVR x-tee teenuseid hetkel Rahandusministeeriumi andmekogu all. X-tee teenused peaks siseteenustena olema samuti riigiteenused.ee skoobis, kuid andmete topeltpidamist tuleks vältida.

![riha_kvr_x-tee_teenused_rm_andmekogu](https://cloud.githubusercontent.com/assets/146800/10606986/24a2cfd0-773f-11e5-9939-6552e1b8f546.PNG)
![riha_kvr_x-tee_teenused](https://cloud.githubusercontent.com/assets/146800/10606989/28289ffe-773f-11e5-8da4-a9a0d259afc6.PNG)

### KVR avaandmete teenused

![opendata](https://cloud.githubusercontent.com/assets/146800/10608722/ec643ca8-7748-11e5-9520-8a25b842f55f.PNG)
https://opendata.riik.ee/dataset/kinnisvararegister
@katrinsolvak, @andreaspapp

**Comment by RRisto** [comment]
RIHA on hetkel ümbertegemisel ning sellega on arvestatud, et lõppkasutajate teenuste kataloog hakkab RIHAga andmeid vahetama. Ei saa välistada, et funktsionaalsus kolib RIHA külge. See selgub RIHA arenduse käigus. Hetkel RIHAs kirjeldatud teenuseid kataloogi importima ei hakka, tihti pole tegemist nende teenustega, mis meie kataloogis olema hakkavad (kirjeldused ei vasta ka meie vormile) ning samuti on RIHA andmekvaliteet alla arvestust (palju vananenud infot). Tulevikus peaks tekkima seos nö RIHAs kirjeldatud teenuste ja lõppkasutajate teenuste vahel (kas see tekib meie kataloogis või RIHAs, on hetkel lahtine).

**Comment by tormi** [comment]
> lõppkasutajate teenuste kataloog hakkab RIHAga andmeid vahetama. Ei saa välistada, et funktsionaalsus kolib RIHA külge.

Kui see kolib RIHA külge, siis mis riigiteenused.ee-sse alles jääb? :)

RM-i infotunnis tekitas andmete mitmekordne kogumine trotsi, see tuleb andmekorje eel läbi mõelda ja lahti kommunikeerida.

**Comment by RRisto** [comment]
See, kus arhitektuuriliselt hakkab kataloog olema, on suht ükskõik (sisu eest vastutame meie). Hetkel ei ole sellist kataloogi nagu meie teeme (lõppkasutajale osutatavad teenused). Mitmekordse kogumise vastu tahamegi oma andmeid RIHAga jms süsteemidega, kus neid vaja on, jagada. RIHA projekti on meie osakond ka kaasatud ning selle põhimõttega ka arvestatakse.

**Comment by tormi** [comment]
> RIHA projekti on meie osakond ka kaasatud ning selle põhimõttega ka arvestatakse.

Tead sa, kas neil on ka mingi avalik issue management?

**Comment by RRisto** [comment]
minu teada mitte

**Comment by RRisto** [comment]
versioonis 2 on võimalik märkida teenusele seosed RIHAs kirjeldatud teenustega
