### ISSUE TITLE
Teenuse staatus ja helpdesk

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#22]
Iga teenuse juures võiks olla lisaks võimalus sisestada järgmine info:
1. viide **teenuse staatus**e infole (sh eelseisvad kavandatud katkestused, ootamatud intsidendid ja nende lahendamise operatiivinfo jne). Näit. http://status.pantheon.io/, https://www.statuspage.io/
2. viide **teenuse helpdesk**ile, kustkaudu teenuse omanik kogub infot teenuse rahulolu, ettepanekute ja vigade kohta ning annab tagasisidet nende alusel kavandatud/tehtud tegevustest. Näit. https://github.com/MKM-ITAO/riigiteenused/.

Võimalik, et neid teenuseid võiks nö baastasemena osutada ka riigiteenused.ee keskkond.

**Comment by tormi** [comment]
Avaandmete teenustele on tagasisidet võimalik anda portaalis opendata.riik.ee:
![opendata_tagasiside](https://cloud.githubusercontent.com/assets/146800/10608433/abc55ab6-7747-11e5-934a-b670a08b3958.PNG)

**Comment by tormi** [comment]
Peab tunnistama, et p.1-le ei ole ma oma rakenduse jaoks head kohta/viidet leidnud. Praegu kasutame selleks rakendusega samas kastis olevat [infoportaali](https://riigivara.fin.ee/lr1/web/guest), aga sellest on vähe kasu, kui kast tervikuna maas on. Mõned kasutavad twitterit, ilmselt saaks ka github'i. 

e-teenuse staatuse kohta info jagamine võiks küll tulevikus olla riigiteenused.ee baasfunktsionaalsus.

**Comment by tormi** [comment]
Teenuse tagasisidet küsib ka [Tallinn teenuse rakenduse](http://www.tallinn.ee/teenused) juures:
![teenused_tagasiside](https://cloud.githubusercontent.com/assets/146800/10663416/e91a036c-78c3-11e5-80f1-6a3adac7abcb.PNG)
(http://www.tallinn.ee/Teenus-Rannavalve-ja-vetelpaaste > Küsimused ja ettepanekud)

**Comment by tormi** [comment]
EMTA uue e-MTA idede korje toimub Google ankeediga, esitatud ideed ja ettepanekud jäävad seetõttu peitu. Saatsin neile ettepaneku liikuda Github-i.
![emta1](https://cloud.githubusercontent.com/assets/146800/10712423/a474308e-7aa3-11e5-8f7e-b1f8b4b9c48e.png)
![emta2](https://cloud.githubusercontent.com/assets/146800/10712425/ab7a2aa0-7aa3-11e5-8eab-e8f0fad55bba.png)
Tausta: http://arileht.delfi.ee/news/uudised/kusitlus-mida-e-maksuameti-kasutajad-tegelikult-tahavad?id=71637781

**Comment by RRisto** [comment]
:+1:

**Comment by RRisto** [comment]
versioonis 2 seda pole. Eeldaks laiemat lähenemist, et asutused üldse hakkaks sedasi tagasisidet koguma

**Comment by tormi** [comment]
Seotud punktiga 2 ( teenuse helpdesk): https://github.com/okestonia/opendata-issue-tracker/issues/71
