### ISSUE TITLE
SIM: Teenuse seisundi klassifikaatori täiendamine

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#23]
Lisada klassifikaator "planeerimisel" (raha ei ole, aga plaan on teha) ning võtta ära klassifikaator "muudatust vaja", kuna see on sisutühi (teenuseid tuleb kogu aeg muuta).

**Comment by tormi** [comment]
> Lisada klassifikaator "planeerimisel"

:+1: , kasutaks "kavandamisel". 

> võtta ära klassifikaator "muudatust vaja", kuna see on sisutühi (teenuseid tuleb kogu aeg muuta)

:+1: See viitab selgelt teenuse versioneerimise vajadusele. Uue versiooni juures saaks viidata, millised muudatused teenuse sisusse sisse viidi. Muudatused on sisuliselt vaja kirjeldada sarnaselt riigiteenused.ee iteratsioonidele, näit. [2. iteratsiooniga kavandatavad muudatused](https://github.com/MKM-ITAO/riigiteenused/milestones/2.%20iteratsioon). See omakorda viitab vajadusele teenuse muudatusvajadusi hallata (sh kavandamisfaasis).

NB! Mitte segi ajada teenusekaardi sisu tehnilise versioneerimisega, millele viitan kandes https://github.com/MKM-ITAO/riigiteenused/issues/2 !

Praegune klassifikaator:
![teenuse_seisund](https://cloud.githubusercontent.com/assets/146800/10663887/b6301802-78c7-11e5-856c-cedacc1549c2.PNG)

**Comment by RRisto** [comment]
versioonis 2 on teenuse seisund ja teenuse kirjelduse seisund lahku viidud
