### ISSUE TITLE
SIM: täiendada rippmenüüga eel-, järeltingimuste ja dokumentide atribuuti

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#24]
Eeltingimus: pakkuda rippmenüüs välja juba olemasolevatest teenustest
Järeltingimus: pakkuda rippmenüüs välja variandid, mis kasu klient teenusest saab
Dokumendid: pakkuda rippmenüüs välja, mis dokumendid väljastatakse selle teenuse tulemusena.

**Comment by tormi** [comment]
> mis dokumendid väljastatakse selle teenuse tulemusena

Kas dokument väljastatakse teenuse või hoopis äriprotsessi tulemusena? St kas võiks öelda, et mingit liiki dokumendi väljastamine ongi eraldi teenus ja niipea kui väljastatakse rohkem kui ühte liiki dokumente, tuleb neid käsitleda eraldi teenustena? Või läheb see liiga pudiks? Teenuste rühmitamine?

@andreaspapp, mõtle ka kaasa.

**Comment by RRisto** [comment]
versioonis 2 on ainult eeltingimused, kus saab viidata olemasolevatele teenustele
