### ISSUE TITLE
SIM: märkida ära väljad, mis on avalikus vaates näha

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#25]
Teenuse sisestamise vormil võiks eraldi märkida ära väljad, mis on nähtavad avalikus teenuse otsingu vaates.

**Comment by tormi** [comment]
Mida siin avaliku teenuse otsingu all mõeldakse, [veebilehte](https://www.mkm.ee/et/teenuste-otsing) või [avaandmeid](https://www.riigiteenused.ee/api/et/all)? Ja mis aspektist see märkimine oluline oleks?

**Comment by RRisto** [comment]
Veebilehte mõeldakse, soovivad kohe sisestamisel näha, mis andmeväljad otsingus välja kuvatakse. On mugavam kui otsingust vaadata, mis andmeväljad kuvatud on.

**Comment by RRisto** [comment]
versioonis 2 on sisseloginud kasutajal võimalik näha, kuidas teenus avalikus vaates välja näeb
