### ISSUE TITLE
SIM: täiendada sihtgrupi kalssifikaatorit

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#27]
Kodaniku asemel võiks olla eraisik/füüsiline isik (kodanik on liiga kitsas mõiste). 
Tuleks lahti kirjutada, kuidas oleme defineerinud erinevad sihtgrupid (kes kuuluvad nende määratluste alla).

**Comment by tormi** [comment]
Seotud: https://github.com/MKM-ITAO/riigiteenused/issues/16#issuecomment-149532944

**Comment by RRisto** [comment]
versioonis 2 on muudetud
