### ISSUE TITLE
Teenuse osutamise kanal andmeobjektiks

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#29]
Teen ettepaneku lisada teenuse osutamise kanalid (RIHA mõistes infosüsteemid) eraldi andmeobjektidena. See võimaldaks koondada kanali teenuste ühisinfo ühte kohta, sh e-kanali RIHA viide, kanali asukoht*, omanik, staatus ja helpdesk (#22) jne.

*- letiteenuste puhul on kanali asukohaks teeninduspunktide võrgustik.

**Comment by RRisto** [comment]
RIHA viitenumbrid on versioonis 2 olemas. Hetkel kanalipõhiselt seda infot ei kogu. Vaatame, kas saame üldse mingit infot RIHAs toodud infosüsteemide kohta
