### ISSUE TITLE
Domain klassifikaatori täiendusettepanek

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#3]
Teen ettepaneku täiendada domainide loetelu valikuga "Riigi kinnisvara".
![domaini taiendamine](https://cloud.githubusercontent.com/assets/146800/10426581/2125e000-70ea-11e5-939a-ae1cb77a2251.PNG)

**Comment by andreaspapp** [comment]
Siit tuleks ära kaotada ka valik "Load ja registreeringud", sest mõlemad eraldi (nii "Load" kui "Registreeringud" on toodud alajaotuse "Tüüp" all.
Lisaks veel, "Load ja registreeringud" ei ole justkui sama tasandi mõiste kui näiteks "Merendus" või "Lennundus". Riigi kinnisvara minu hinnangul mõistetasandina sobib.

**Comment by tormi** [comment]
@andreaspapp :+1:, domain peaks olema valdkondade jaoks ;) Võimalik, et sobivam oleks isegi lihtsalt "Kinnisvara".

**Comment by tormi** [comment]
Lisaettepanekud:
- `Avalik teenuste arendamine` > `Avalikud teenused` (hetkenimetuses lisaks typo, peaks olema "Avalik**e**)
- `Ettevõtte loomine ja arendamine` > `Ettevõtlus`

**Comment by RRisto** [comment]
Typo parandasin ära ja ettevõtluse osas tegin ka muudatuse (avalikku vaatesse peaks tekkima mõne aja pärast).

**Comment by RRisto** [comment]
Lubade ja registreeringute osa võtan arvesse ning pärast esmast kirjeldust saab mõelda selle ära kaotamisele. Praegu ära kaotades tekivad teenuste kirjeldusse nn augud. Riigi kinnisvara klassifikaatori lõin (peaks lähiajal avalikku vaatesse ilmuma).

**Comment by tormi** [comment]
Tänud! Kas jätame selle kande lahti või teeb lubadele follow-up kande?

**Comment by RRisto** [comment]
Las olla lahti, on lihtsam jälgida, mida pean tulevikus arvesse võtma

**Comment by tormi** [comment]
Riigi kinnisvara vs Kinnisvara me ei arutlenud. Kuidas näed, kas on ka selliseid kinnisvaravaldkonna teenuseid, mis ei seostu riigi kinnisvaraga?

**Comment by RRisto** [comment]
Hetkel ei oska pakkuda, kuid arvan et pigem  mitte, kinnisvaraga seotud teenused on vast rohkem ohutusega (tehnilise järelevalve) seotud. Eks paistab, mis kaardistamise käigus välja tuleb.

**Comment by tormi** [comment]
Kas KOV-id/avalik sektor laiemalt tuleb ka skoopi? Kui jah, siis sobiks eesliiteta "Kinnisvara" paremini. Näit. [Tallinna kinnisvararegistri](https://riha.eesti.ee/riha/main/inf/tallinna_kinnisvararegister) teenused ei ole riigi kinnisvara teenused.

**Comment by RRisto** [comment]
Hetkel mitte. Kõigepealt üritame asja kitsamas seltskonnas tööle saada. Pärast võib mõelda KOVide ja muude asutuste peale.

**Comment by RRisto** [comment]
Muutsin lubade ja registreeringute klassifikaatori ära "Erinõuetega tegevusalad". Hakkas segadust tekitama. Seega see teema otseselt maas. Edasised ettepanekud teenuse tüübi ja tegevusvaldkonna kohta oodatud punkti #13
