### ISSUE TITLE
riigiteenused.ee kirjeldamine RIHA-s

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#30]
Tundub, et hetkel on riigiteenused.ee RIHA-s kirjeldamata. Või on see [www.mkm.ee avaliku veebi](https://riha.eesti.ee/riha/main/inf/avalik_veeb_www_mkm_ee) ([VP](https://riha.eesti.ee/riha/main/inf/valitsusportaal)) osa? Pigem siiski mitte.

**Comment by RRisto** [comment]
Uurisin RIAst teemat: 
- Küsimus:
  Mul tekkis küsimus RIHAs registreerimise kohta. Nimelt on meil loodud veebipõhine Drupalil baseeruv [tööriist](www.riigiteenused.ee) teenuste kaardistamiseks. Selles keskkonnas saavad kasutajad kirjeldada avalikke teenuseid. Avalikus vaates saab kirjeldusi näha hetkel MKMi veebis (tulevikus ka teistes valitsusportaali põhja kasutavates ministeeriumites/asutustes).  Masinloetav vaade kirjeldatud teenustest on nähtav [siin](https://www.riigiteenused.ee/api/et/all). Nüüd ongi tekkinud küsimus, kas see töövahend peaks RIHAs olema kirjeldatud? Mingis mõttes on see osa valitsusportaalist (kasutab selle stiili ja platvormi, andmeid kuvatakse valitsusportaali veebi kaudu). Samuti pole selle loomise aluseks õigusakt.
- Vastus: RIHAs peab olema infosüsteem kirjeldatud juhul kui see on nii õiguslikult sätestatud või juhul kui pakutakse/kasutatakse X-tee teenuseid. Esimene vastus, ma saan aru, on ei. Kui X-teega ei ole kirjeldatud töövahendil pistmist, siis Te võite, kuid ei ole kohustatud seda RIHAs registreerima.

Seega otsest kohustust seda RIHAs registreerida ei ole.

**Comment by tormi** [comment]
Siis tuleks leida vastus küsimusele, kas kavandate riigiteenuste (RT) andmeid ka x-tee kaudu pakkuda? Hetkel on selline jäik regulatsioon, et riigi infosüsteemi kuuluvad andmekogud peavad andmevahetuseks x-teed kasutama.

Kui [riigi kinnisvararegister](https://github.com/kinnisvara/RKVR/) sooviks näiteks tarbida RT andmeid (või vastupidi, vt näiteks https://github.com/MKM-ITAO/riigiteenused/issues/29 letiteenuse selgitust) selleks, et seostada avalikud teenused teenuse osutamiseks vajaliku kinnisvarakeskkonnaga, tuleb seda hetkel teha x-teed kasutades. See aga viitab, et RT peaks andmeid pakkuma ka x-tee kaudu, mis omakorda on võimalik vaid RIHA-s registreerituna.

**Comment by tormi** [comment]
Ma ise näen, et [AvTS regulatsioonist](https://www.riigiteataja.ee/akt/avts#para43b9lg5) tulenev x-tee kohustuslikkus riigi infosüsteemidele on praegusel juhul ilmne liiasus. Miks ei võiks ka riigi infosüsteemi kuuluvad rakendused teatud juhtudel andmeid vahetada [AvTS § 29 lg 3](https://www.riigiteataja.ee/akt/avts#para29lg3) alusel? Andmete avaandmetena pakkumise võimekus on ju nagunii vaja välja arendada. @andreskytt?

**Comment by RRisto** [comment]
Teenuste kataloogi prototüübi loomisel sai sel teemal RIA inimestega (põhiliselt Priit Parmakson) suheldud ning tundus ebamõistlik täiesti avalikke andmeid mööda kõige turvalisemat toru pidi liigutada.

**Comment by PriitParmakson** [comment]
Siin peaks vaatama RIHA ja RIHAs registreerimise kohustuse eesmärki. RIHA on loodud riigi infosüsteemi haldamise (=juhtimise) erinevate toimingute hõlbustamiseks. Juhtimise eelduseks on teave juhitava objekti kohta. Teiselt poolt on RIHAs kirjeldamine infosüsteemide omanikele koormus. Seetõttu peab vaatama, kas eesmärki saaks täita väiksema koormusega. RIHA uues kontseptsioonis lähtume sellest, et asutused panevad oma süsteemide metaandmed (=kirjeldused) ise avaandmetena välja; RIHA harvester (andmekorje rakendus) korjab need kesksesse varamusse kokku ja teeb kõigile kergesti leitavaks. Praegu küll on ülalnimetatud kriteeriumid (süsteemi otsene nimetamine õigusaktis või X-teel olek), kuid tunnistagem, et need on pelgalt instrumendid RIHAs kirjeldamise koormuse ohjeldamiseks.

**Comment by RRisto** [comment]
Panen teema kinni, riigiteenuste projektiga neid küsimus ära ei lahenda. Riigiteenused ise on valitsusportaali lisamoodul, mida tulevikus tahame kõikidesse ministeeriumite kodulehtedele viia ning seega ei hakka teenustekataloogi eraldi ka RIHAs registreerima
