### ISSUE TITLE
Teenuse sündmus autocomplete term widgetina

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#31]
Teen ettepaneku asendada teenuse sündmuse tekstiväli taksonoomia väljaga, kus sisendmalliks on `autocomplete term widget`. See võimaldab teistel teenuste kirjeldajatel juba olemasolevaid sündmusi kasutada. Samal ajal ei kirjutata sisestajale jäika taksonoomiat ette.
### AS IS (tekstiväli)

![teenuse sundmus](https://cloud.githubusercontent.com/assets/146800/10761209/fbb8c46e-7cc8-11e5-81d2-5dd8ddacc3d6.PNG)
### Drupal 7 sisutüübi haldusvorm, kus saab autocomplete term widgeti seadistada

![term reference](https://cloud.githubusercontent.com/assets/146800/10761226/05264b84-7cc9-11e5-845a-b92516e542fa.PNG)
### TO BE (taksonoomia väli)

![autotagging](https://cloud.githubusercontent.com/assets/146800/10761229/0c269b64-7cc9-11e5-8f25-9d55e437a8c3.PNG)

**Comment by RRisto** [comment]
Kuna hetkel arendusega probleeme (vanade vigade parandamine võtab palju aega), siis hetkel ei hakka seda lisatööd tellima. Küll aga tuleviku vaates vajalik lahendus.

**Comment by tormi** [comment]
Seda oleks just praegu vaja tegelikult, hiljem on teenused sisestatud ja andmetüüpi keerulisem muuta

**Comment by RRisto** [comment]
Reaalsus on see, et arendaja ei suuda olemasolevaid probleeme lahendada. Kui nad need suudavad ära lahendada, saame selle lisaarenduse tellida. Samuti pole see kaardistuse praeguses etapis kõige olulisem lahter nii et pole hullu, kui hetkel seda widgetit ei saa sinna.

**Comment by tormi** [comment]
UK omavalitsuste teenuste elusündmuste klassifikaator: http://standards.esd.org.uk/? > Life Events

**Comment by RRisto** [comment]
elusündmuste temaatikaga hakkame tegelema selle aasta jooksul, siis tekib ehk ka loetelu elu- ja ärisündmustest

**Comment by RRisto** [comment]
kui uuesti lauale tõusetub, siis lisame versiooni 3
