### ISSUE TITLE
riigiteenused.ee-le avalik teenuste koondvaade

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#32]
Ettepanek lisada riigiteenused.ee-le avalik teenuste koondvaade, et kodanikul jne tekiks teenuste sirvimiseks üks koht, mitte 1+n valitsemisala veebi. Lisaks on näiteks fin.ee veel [VP](https://riigikantselei.ee/et/valitsusportaal)-le üle viimata ja seetõttu ei olegi seni võimalik RM teenuseid välja kuvada.

**Comment by RRisto** [comment]
Hetkel on selleks kohaks MKMi koduleht. eraldi keskkonda selle jaoks tegema ei hakka, vaade peaks tekkima sinna, kus seda vaja on (nt eesti.ee või valitsusveebi). Esialgu on kliendile abiks seegi, kui iga ministeeriumi/asutuse veebi hakkab tekkima ühesugune ülevaade teenustest. Kas RMil on plaanis minna VP-le üle?

**Comment by tormi** [comment]
> VP-le üle?

Jah.

**Comment by tormi** [comment]
> kus seda vaja on (nt eesti.ee või _valitsusveebi_)

@oojamaa, mida RK arvab? Mu arust oleks siiski mõistlik riigialamale kogu teenuste vaade ühest kohast ette anda.

**Comment by RRisto** [comment]
teeme koostööd eesti.ee tiimiga, kus teenuste vaade kliendile võiks hakata tekkima eesti.ee-s: https://github.com/MKM-ITAO/Teenuste-kataloogi-RIHA-ja-Eesti.ee-seosed
