### ISSUE TITLE
Maaelumin:Võimalus lisada ühele teenusele mitu tegevusvaldkonda

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#33]
Ühele teenusele võiks olla võimalik lisada mitu tegevusvaldkonda. Võib-olla oleks vajalik lisada ka mitu teenuse tüüpi.

**Comment by tormi** [comment]
Kas toodi ka näide?

**Comment by RRisto** [comment]
Näiteks kalandus ja välisvahendid (kalanduses jagatavad eurotoetused)

**Comment by RRisto** [comment]
versioonis 2 jäi siiski üks tegevusvaldkond. tegemist pole laiema probleemiga. vajadusel saab iteratsioonis 3 pildile tuua.
