### ISSUE TITLE
ID-kaart ja Mobiil-ID andmetöötleja isikutuvastuseks

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#34]
Teen ettepaneku isikutuvastuseks kasutusele võtta  ID-kaart ja Mobiil-ID. Vastavad Drupal 7 moodulid on kättesaadavad siin: https://github.com/opendata-ee/dgu_d7/tree/look_feel_est/modules/custom/digidoc

**Comment by RRisto** [comment]
versioonis 2 olemas
