### ISSUE TITLE
Teenuse drafti ei ole võimalik muuta/avaldada

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#35]
Lisasin [uue teenuse kirjelduse](https://www.riigiteenused.ee/et/node/311/) draftina (lülitasin _Avaldatud_ linnukese välja, sest soovisin kande enne avaldamist koos teistega üle vaadata (tavapärane avaldamise töövoog):

![riigiteenused ee_staatus_avaldamata](https://cloud.githubusercontent.com/assets/146800/10882346/aa8405f0-8172-11e5-8364-9b78622e051e.PNG)

Teenuse sisu:

![riigiteenused ee_teenus](https://cloud.githubusercontent.com/assets/146800/10882563/80ae2d9e-8174-11e5-83e0-0d3e97ff8802.PNG)

Pärast teenuse salvestamist aga ei ole mul teenuse muutmisvormile enam juurdepääsu:

![riigiteenused ee_content](https://cloud.githubusercontent.com/assets/146800/10882517/1c06ae84-8174-11e5-9aed-e2d5b2556b91.PNG)

**Comment by Airir5** [comment]
Meie vaates on kirjeldatud teenus olemas. Proovi lehte värskendada või siis algseadistada filtreid. 
![rm teenus](https://cloud.githubusercontent.com/assets/15089095/10882705/9949170a-8175-11e5-9f19-672256a447c2.png)
Lisaks veel, et kui teenust ei soovi veel avaldada, siis valida teenuse seisund "loomisel".

**Comment by tormi** [comment]
> Meie vaates on kirjeldatud teenus olemas. Proovi lehte värskendada või siis algseadistada filtreid. 

Filtrid on kõik _any_, refresh ei aita:

![riigiteenused ee_content2](https://cloud.githubusercontent.com/assets/146800/10883420/8cada268-817a-11e5-95db-5b53c7ef636a.PNG)

Ilmselt on autenditud kasutajale jäänud lisamata vastavad õigused (kollasega):

![riigiteenused ee_staatus_avaldamata_oigused](https://cloud.githubusercontent.com/assets/146800/10883443/b0f0abfc-817a-11e5-8713-dc11b6e9a657.PNG)

> kui teenust ei soovi veel avaldada, siis valida teenuse seisund "loomisel".

Hetkel käsitletakse teenusekaardi täitmist ja teenuse enda kavandamist tõesti samas klassifikaatoris: _Loomisel - teenus/teenuse kirjeldus on loomisel ning seda ei avalikustata._ See ei ole mõistlik, sest sellisel juhul ei ole võimalik kavandatavate teenuste infot avaldada. Tegin muudatusettepaneku: #37.

**Comment by tormi** [comment]
Ma liigitaks selle veaks.

**Comment by RRisto** [comment]
Kuna hetkel on arendajaga selline loogika kokku lepitud, siis selles mõttes see viga pole.

**Comment by tormi** [comment]
[Õigusi](https://riigiteenused.ee/admin/people/permissions) saab ju rakenduse admin hallata? St lisada _sisestaja / teenuse omaniku_ rollile linnuke reale _View own unpublished content_?

**Comment by tormi** [comment]
Ilmselt tuleb üle vaadata ja puudumisel lisada linnuke ka reale _Teenus: Edit own content_.

**Comment by tormi** [comment]
Hmm, kas muutsite midagi? Hetkel ei näe ma enda draftina lisatud teenust enam ka [otseviite](https://www.riigiteenused.ee/et/node/311/) abil (varem nägin, vt ekraanipilt ülal). Viitel kuvatakse nüüd veateadet `Sul puudub õigus antud lehte vaadata.`

**Comment by RRisto** [comment]
Proovisime jah erinevaid variante (et kas avaldamise linnutamine mõjutab kuvamist või mitte). Sellepärast võis ka ära kaduda. Räägin sellest täna ka juhtrühmas. Loodan et järgmise nädala jooksul saab probleem lahendatud.

**Comment by RRisto** [comment]
Kas nüüd on probleem lahendatud?

**Comment by tormi** [comment]
Jah, tänud!

**Comment by tormi** [comment]
Avan uuesti, sest sama probleem on teenusega https://www.riigiteenused.ee/et/teenus/riigi-kinnisvararegistri-avaandmed
Valisin "Avaldamise seaded" > Avaldatud", kuid salvestamise hetkel ilmselt kontrollitakse mingit ärireeglit, mis muudab staatuseks "Pole avaldatud". Vt lisaks redaktsioonide logi, https://www.riigiteenused.ee/et/node/751/revisions

**Comment by tormi** [comment]
Sama probleem: https://www.riigiteenused.ee/et/teenus/riigi-kinnisvara-andmete-haldamine

**Comment by tormi** [comment]
Veel: https://www.riigiteenused.ee/et/teenus/riigi-kinnisvara-andmete-x-tee-teenus-kvrotsing

**Comment by Airir5** [comment]
Selleks, et teenus avaldatakse, peab administraator (MKM) selle esmalt üle vaatama ning seejärel ise avaldama. Seetõttu pärast teenuse kirjeldamist ning salvestamist, teenus automaatselt ei avaldu.

**Comment by tormi** [comment]
Selge. See tuleks ka kasutajale teatena kommunikeerida ja avaldamise linnuke ära võtta.

**Comment by tormi** [comment]
@Airir5 , kas saaks need operatiivselt üle vaadata?

**Comment by Airir5** [comment]
Oleme avaldamise protsessi kõigil koolitustel lahti seletanud. 
Vaatasin üle ja saatsin tagasiside e-kirjana.
