### ISSUE TITLE
Teenuse kirjelduse välja pikkus ebapiisav

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#36]
Teenuse kirjelduse välja pikkus (245 tähemärki) on ebapiisav, peaks olema _long text_.

**Comment by RRisto** [comment]
Kas oskad tuua mõne näite, kus pikkus ebapiisav?

**Comment by tormi** [comment]
Proovisin RM teenuse [001](https://github.com/MKM-ITAO/riigiteenused/issues/35) kirjeldusele lisada [KVR PM § 6](https://www.riigiteataja.ee/akt/128122010002#para6) lg 1 teksti veidi kohendatud kujul. Võimalik, et ei peagi pikem olema, aga tundus, et võiks olla sama pikkusega nagu teenusekaardi vormi väljad "_Lisainfo ja märkused ..._".

**Comment by RRisto** [comment]
Eks oleks parem kui oleks lühem, kuid kui esmane kaardistus tehtud, saab ettepaneku läbi analüüsida.

**Comment by RRisto** [comment]
versioonis 2 on piirang sama (220 tähemärki). Pole juhtumeid olnud, kus selle piiranguga pole õnnestunud arusaadavat teenuse nime kirjutada.
