### ISSUE TITLE
Eraldada teenuse staatuse ja teenusekaardi staatuse haldamine

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#37]
Hetkel on nii **teenusekaardi staatus** kui **teenuse enda staatus** samas klassifikaatoris: 

![teenuse seisund](https://cloud.githubusercontent.com/assets/146800/10883277/8997435a-8179-11e5-8b1f-de4726629664.PNG)

See ei ole mõistlik, sest sellisel juhul ei ole võimalik selliste teenuste infot avaldada, mis on kavandamisel ja mille teenusekaart on korrektselt täidetud ning mille peatsest osutamisest ja osutamise tingimustest on teenuse omanikul soov teada anda (ehk ka tagasisidet koguda). Teen ettepaneku teenusekaardi staatusena kasutada kande avaldamise seadete staatust _Avaldatud / Pole avaldatud_:

![riigiteenused ee_staatus](https://cloud.githubusercontent.com/assets/146800/10883328/f78c6624-8179-11e5-9ec7-ae8f58d620ad.PNG)

**Comment by tormi** [comment]
Kui see on ok, siis tuleb ka kavandatavaid ja arhiveeritud teenuseid välja näidata (sh filtreerida seisundi järgi).

**Comment by RRisto** [comment]
Peaks olema seotud punktiga #39 Arendajale on teada antud, ootan nende poolset parandust.

**Comment by tormi** [comment]
Vaatasin, et olen teenuse staatust kasutanud siin ja #22-s eri tähendusega. Siin pidasin silmas pigem teenuse elukaart. Muuseas, üks alternatiiv oleks kasutada UK e-teenuse [elukaare klassifikaatorit](https://www.gov.uk/service-manual):
- Discovery
- Alpha
- Beta
- Live
- Retirement

**Comment by tormi** [comment]
US 18F kasutab sama: https://18f.gsa.gov/dashboard/

**Comment by RRisto** [comment]
versioonis 2 on olemas. hetkel pole UK lähenemist kasutusele võtnud. See eeldaks olulisemalt tsentraalsemat juhtimist
