### ISSUE TITLE
Kui ministeeriumi ja allasutuse nimi teenuse vormil sama, ei kuva sisestajale sisu all sisestatud teenust

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#39]
Kui allasutuse ja  ministeeriumi (nt rahandusministeerium) nimi on sama, siis ei kuva teenuse sisestajale "sisu" all teenuse kirjeldust.

**Comment by tormi** [comment]
Kas ka avaldatud kannete puhul?

**Comment by tormi** [comment]
> Kui allasutuse ja ministeeriumi (nt rahandusministeerium) nimi on sama, siis ei kuva teenuse sisestajale "**sisu**" all teenuse kirjeldust

Mida sisu all silmas pead? Minu ekraanipildil kandes https://github.com/MKM-ITAO/riigiteenused/issues/35 kirjeldust ju kuvatakse, kuigi allasutuse ja ministeeriumi nimi on RM. Tõsi, enam ei näe ma ka drafti, vt https://github.com/MKM-ITAO/riigiteenused/issues/35#issuecomment-153977079.

**Comment by RRisto** [comment]
Seal on mingi teema, et süsteem läheb lolliks kui ministeeriumi ja allasutuse nimi on sama. Adminnina näen neid teenuseid, kuid sisestajad ei näe. Arendaja on probleemist teadlik ning tegeleb parandamisega. Kuna hetkel on live keskkond igasugu vigu täis, siis ei oska täpselt öelda, miks sul ka draft ära kadus. Järgmise uuendusega peaksid vead kaduma (loodetavasti järgmise nädala jooksul).

**Comment by RRisto** [comment]
Probleem peaks olema lahendatud. Ministeeriumi nimi, mis tähistab kõrgemat taset, nimele on lõppu lisatud sõn "haldusala", ministeerium, kui teenuse osutaja puhuö jäeti nimi samaks. Nüüd peaks teenused olema kuvatud.

**Comment by tormi** [comment]
Nüüd on kasutajaliides natuke vastuoluline - ministeeriumi asemel peaks ehk olema haldusala:
![haldusala](https://cloud.githubusercontent.com/assets/146800/11469816/d43bdc06-9761-11e5-95bf-36502642339a.PNG)

**Comment by RRisto** [comment]
Hea tähelepanek

**Comment by tormi** [comment]
Ja allasutuse asemel lihtsalt asutus.

**Comment by RRisto** [comment]
versioonis 2 olemas
