### ISSUE TITLE
Kasutajaliidese tõlkimine

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#4]
Kasutajaliideses on palju eesti keelde tõlkimata sõnu, võiks [ära tõlkida](https://www.riigiteenused.ee/et/admin/config/regional/translate) enne andmekorjet.

**Comment by RRisto** [comment]
Tõlkega hetkel probleeme. Loodetavasti saab asjad korda lähiajal.

**Comment by andreaspapp** [comment]
Kui mina kunagi ammu proovisin, oli tõlgitud...ju oli IT-meestel korraks midagi segamini läinud.
14.10 seisuga kasutaja RM_kastutaja1 vaates asi korras.
Küll aga on by default kuvatud mingi salapärane veateade müstilise temporary faili laadimise kohta...

**Comment by tormi** [comment]
Tegin veateatele eraldi kande #9

**Comment by RRisto** [comment]
versioonis 2 tõlkimine parandatud
