### ISSUE TITLE
HTM: regulatsioonis lingi asemel lingitav seaduse nimi

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#42]
Regulatsiooni väljale võiks lisada lingi asemel hoopis seaduse nime, mis on lingitav.

**Comment by tormi** [comment]
[Link moodul](https://www.drupal.org/project/link) võimaldab seda:
![link](https://cloud.githubusercontent.com/assets/146800/11033959/4b4f246a-86f0-11e5-81bd-958ae440b151.PNG)
Ilmselt peaks jätma võimaluse sisestada 1+n alust, näitena Tallinna teenuste baasi [ühe teenuse õigusaktid](http://www.tallinn.ee/Teenus-Maa-maksustamise-alusandmetest-teavitamine#oigusaktid):
![oa](https://cloud.githubusercontent.com/assets/146800/11033994/9881c7b0-86f0-11e5-8f2c-158bb4aacb20.PNG)

**Comment by RRisto** [comment]
versioonis 2 olemas
