### ISSUE TITLE
Rahvusraamatukogu: Ta tahaks lisalahter info jagamise kohta teiste süsteemidega.

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#43]
Ta tahaks lisalahtrit, kus oleks kirjas, kas sellel e-teenusel on mingi API, x-tee või muu võimalus, et infot jagada teiste süsteemidega. Loomulikult jääks lubamine selle teenuse omanikule, aga põhimõtteline võimekus peaks kirjas olema.

**Comment by tormi** [comment]
See tundub olevat #6 duplikaat. Vt. ka #29, #26, #21, #18.

**Comment by tormi** [comment]
Lisaks tuleks selle kande lahendamisel üle vaadata see kkk punkt: https://github.com/MKM-ITAO/riigiteenused/blob/master/Korduma%20kippuvad%20k%C3%BCsimused/korduma%20kippuvad%20k%C3%BCsimused.md#kuidas-suhtuda-kahe-infos%C3%BCsteemi-vaheliste-andmete-vahetamisega-kas-see-on-teenus

**Comment by RRisto** [comment]
versioonis 2 olemas väli "RIHA viitenumber", kuhu saab panna viite RIHAs kirjeldatud infosüsteemile/tehnilise teenusele, mis toetab avaliku teenuse osutamist.
