### ISSUE TITLE
Infoühiskonna teenuse osutaja kohta edastatav teave

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#44]
[Infoühiskonna teenuse seaduse § 4](https://www.riigiteataja.ee/akt/112072014048#para4) loetleb andmed, mis tuleb [infoühiskonna teenuse](https://www.riigiteataja.ee/akt/112072014048#para2) kasutajale kättesaadavaks teha. 

Kontrolliks üle, kas nõue laieneb ka käesoleva projekti raames kirjeldatavatele avalikele e-teenustele (st kas avalik e-teenus = infoühiskonna teenus) ja kas nõude peaks lahendama iga teenuse juures eraldi või riigiteenused.ee projekti raames? MKM teenuste [avalikus liideses](https://www.mkm.ee/et/teenuste-otsing) neid andmeid nõutaval kujul esitatud ei ole:
![mkm_teenused](https://cloud.githubusercontent.com/assets/146800/11242479/9820004a-8e0a-11e5-9075-dc1403463532.PNG)

_§ 4.  Teenuse osutaja kohta edastatav teave_

 _(1) Teenuse osutaja on kohustatud tegema teenuse kasutajale vahetult ja püsivalt kättesaadavaks vähemalt järgmise teabe:
 1) teenuse osutaja nime, registrikoodi ja vastava registri nime, teenuse osutaja aadressi ja muud kontaktandmed, sealhulgas elektronposti aadressi;
 2) registreeringu numbri, kui vastaval tegevusalal tegutsemiseks on seadusega sätestatud majandustegevuse registris registreerimise nõue, või tegevusloa numbri;
 3) viidete puhul teenuse tasu suurusele teabe selle kohta, kas need sisaldavad makse ja tarnekulusid._

 _(2) Reguleeritud kutsealal tegutsev teenuse osutaja on kohustatud lisaks käesoleva paragrahvi lõikes 1 sätestatule tegema teenuse kasutajale vahetult ja püsivalt kättesaadavaks järgmise teabe:
 1) kutseorganisatsiooni või -liidu nimetuse, mille liige ta on seoses osutatava teenusega;
 2) kutse ja liikmesriigi nime, kus see omistati;
 3) viite teenuse osutaja tegevuskoha liikmesriigis kohaldatavatele kutsealastele nõuetele koos nende nõuete tekstidega tutvumiseks vajalike viidetega._

**Comment by RRisto** [comment]
Avalikele teenustele see nõue minu teada ei laiene, pigem peaks see seadus puudutama [teenuseid](https://www.riigiteataja.ee/akt/112072014048#para2), mida osutab erasektor:  teenus, mida osutatakse majandus- või kutsetegevuse raames teenuse kasutaja otsesel taotlusel ... Hetkel ei ole plaanis avalikele teenustele seda nõuet rakendada.

**Comment by tormi** [comment]
Vaataks selles valguses näiteks [tuleohutuse enesekontrolli aruannete keskkonnas](https://tuleohutusaruanne.ee/) pakutavat _tuleohutusaruande esitamise teenust_.

#### Tingimus

_Infoühiskonna teenus on teenus, mida osutatakse majandus- või kutsetegevuse raames teenuse kasutaja otsesel taotlusel ja mille puhul andmeid töödeldakse, säilitatakse ja edastatakse digitaalkujul andmete töötlemiseks ja säilitamiseks mõeldud elektrooniliste vahendite abil, kusjuures osapooled ei viibi üheaegselt samas kohas. Infoühiskonna teenus peab olema täielikult üle kantud, edastatud ja vastu võetud elektrooniliste sidevahendite abil._

#### Vastavus
- _osutatakse majandus- või kutsetegevuse raames_ - jah, vt [tuleohutuseksperdi kutsestandardit](http://www.kutsekoda.ee/et/kutseregister/kutsestandardid/10451760) ja [päästeteenistujate kutsesobivuse nõudeid](https://www.riigiteataja.ee/akt/103032011026?leiaKehtiv#para4)
- _teenuse kasutaja otsesel taotlusel_ - ilmselt jah, sest on [tuleohutuse seadusest tulenev nõue](https://www.riigiteataja.ee/akt/129062014086#para4)

Aga isegi kui see nii ei ole, siis minu hinnangul on minimaalselt § 4 lg 1 punktis 1 toodud andmestik mõistlik teenuse kaardil esitada.

**Comment by RRisto** [comment]
teenuse osutajal on võimalik see info kataloogi sisestada, kui tegemist on tema avaliku teenusega
