### ISSUE TITLE
Warning: Missing argument 1 for _rt_teenus_get_all_teenused()

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#46]
Lehel https://www.riigiteenused.ee/et/statistika/allasutus veateade:
`
    Warning: Missing argument 1 for _rt_teenus_get_all_teenused() funktsioonis _rt_teenus_get_all_teenused() (rida 128 / /var/veeb/riigiteenused/web/profiles/riigiteenused/modules/custom/rt_teenus_api/rt_teenus_api.module).
    Notice: Undefined variable: language funktsioonis _rt_teenus_get_all_teenused() (rida 129 / /var/veeb/riigiteenused/web/profiles/riigiteenused/modules/custom/rt_teenus_api/rt_teenus_api.module).
    Notice: Undefined variable: language funktsioonis _rt_teenus_get_all_teenused() (rida 133 / /var/veeb/riigiteenused/web/profiles/riigiteenused/modules/custom/rt_teenus_api/rt_teenus_api.module).
`

**Comment by RRisto** [comment]
Kas link http://www.riigiteenused.ee/et/statistika/allasutus töötab?

**Comment by tormi** [comment]
See suunab https-ile, mis nüüdseks töötab taas veateateta.
