### ISSUE TITLE
Otsingu filtri "Asutus" muutmine

### ISSUE THREAD

**Issue by Airir5** [MKM-ITAO/riigiteenused#47]
Hetkel on seadistatud otsingu filter "asutus" teenuste avalikus vaates (http://mkm.ee/et/teenuste-otsing) nii, et kui lisada rohkem kui üks asutus, otsib kataloog vasteid nendele teenustele, mida pakutakse ühiselt mõlema asutuse poolt. Ettepanek on muuta filter nii, et kui lisada rohkem kui üks asutus, leiab kataloog vasted kõikidele teenustele vastavatest asutustest.

**Comment by RRisto** [comment]
hetkel lives enam probleemi pole, otsib vasteid kõikide filtrisse valitud asutuste teenuste seast
