### ISSUE TITLE
Portaali ja iseteeninduse vahe?

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#49]
Mis vahe on portaalil ja iseteenindusel? Mõlemat on kasutatud nii passiivse kui aktiivse veebirakenduse liigitamisel.

**Comment by RRisto** [comment]
Portaali all oleme rohkem silmas pidanud veebilehte, mis on mingile teemale pühendatud (nt ohutusportaal) ning põhiliselt saad sealt infot. Iseteenindus on koht kuhu pead sisse logima ning saad juba aktiivsemalt teenust tarbida kui ainult infot lugedes.

**Comment by tormi** [comment]
Selge, see vajab siis selgitamist. Siin mõned portaalina esitatud teenused, mis tegelikult liigituvad iseteeninduse alla: 
![rt ee_kanalid](https://cloud.githubusercontent.com/assets/146800/12292991/3cf45228-b9f9-11e5-9376-d313f120f76c.PNG)

**Comment by RRisto** [comment]
tänud viitamast, saame omanikele tagasisidet anda

**Comment by RRisto** [comment]
üritan kuu jooksul teenuste üldkoordinaatoritele põhjalikku tagasisidet anda nende haldusala teenuste kohta
