### ISSUE TITLE
Uue teenuse lisamise nupp viitab testkeskkonnale

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#5]
Aadressil https://www.riigiteenused.ee/et/teenuste-otsing asuv uue teenuse lisamise nupp viitab [testkeskkonnale](http://test.riigiteenused.ee/et/node/add/teenus).
![lisa teenus](https://cloud.githubusercontent.com/assets/146800/10426746/b9499dc6-70eb-11e5-8394-3dbe5fe2a1f0.PNG)

**Comment by RRisto** [comment]
Viimase uuendusega on viga parandatud.
