### ISSUE TITLE
Sorteeri teenuse otsingus tegevusvaldkonnad alfabeetiliselt

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#51]
Sorteeri teenuse otsingus tegevusvaldkonnad alfabeetiliselt - lihtsustab otsimist.
![riigiteenused ee_tegevusvaldkonnad](https://cloud.githubusercontent.com/assets/146800/12386363/b416da92-bdcd-11e5-919b-4c2688fd6c00.PNG)

**Comment by RRisto** [comment]
versioonis 2 olemas
