### ISSUE TITLE
Juba avaldatud teenuseid muutes värkendatakse andmeid automaatselt, teenus ei kao avalikust vaatest

### ISSUE THREAD

**Issue by Airir5** [MKM-ITAO/riigiteenused#53]
Hetkel juba avaldatud teenustest muutusi tehes kaob teenus avalikust vaatest, kuniks administraator vaatab need üle ning avaldab. Parema ülevaatuse tagamiseks jätta teenus üles ja  kui täiendatakse siis värskendatakse lihtsalt teenuse andmeid. Ehk ei teki sellist olukorda, kus teenust lihtsalt ei ole. See tekitab ka klientides kindlasti segadust. 
Hetkel teenused kaovad ja tekivad ja väga keeruline on ülevaadet omada.

**Comment by tormi** [comment]
Võimalik lahendus on kasutusele võtta https://www.drupal.org/project/workbench_moderation

![workbench-moderation-screenshot](https://cloud.githubusercontent.com/assets/146800/13318198/160fb9f0-dbc2-11e5-9a53-9da3a1014e12.png)

**Comment by RRisto** [comment]
versioonis 2 olemas
