### ISSUE TITLE
Koordinaatori vaade

### ISSUE THREAD

**Issue by RRisto** [MKM-ITAO/riigiteenused#56]
RIA ettepanek: Selline ettepanek – kas oleks ehk kataloogi haldamise mõttes kasulik/vajalik tekitada kataloogi halduritele analoogne vaade nagu manuses. Erinevus siis selles, et mis välju seal kuvataks (kindlasti peaks saama väljade järgi filtreerida) - teenuse omanik, osakond, tüüp, sihtgrupp, seisund jms). Ehk, et mugavam oleks kataloogi hallata kui ees oleks kogu nimekiri olemasolevatest teenustest (filtreeritav), välju võiks ehk kasutaja saada ise olemasolevatest väljadest vabalt vaatesse lisada – nö personaliseeritud vaade  ![screen shot 2016-02-08 at 12 50 55](https://cloud.githubusercontent.com/assets/8947407/12886121/e0e20432-ce73-11e5-8168-680a31c7ac6c.png)

**Comment by tormi** [comment]
:+1:

**Comment by RRisto** [comment]
versioonis 2 olemas
