### ISSUE TITLE
Koordinaatori vaade vol 2

### ISSUE THREAD

**Issue by AnneliT** [MKM-ITAO/riigiteenused#57]
1) Võiks olla võimalus muuta teenuse omaniku andmeid mitmel sama omaniku teenusel korraga. St kõigepealt otsinguga leiad omanik x-i kõik teenused, muudad ühes teenuses omaniku andmed ja siis tekib valik, kas muudad ainult ühekordselt või kõikides selle inimese teenuste kirjeldustes. Vajalik teenuse omaniku vahetumisel, et vältida käsitööd teenuste juures ükshaaval omaniku andmete muutmisel. 
2) Teenuse omaniku andmed nagu tel nr ja ametinimetus võiksid olla kataloogis läbivalt näiteks nimega seotud. St kui ma uuel teenusel sisestan omaniku nime siis väljad tel nr ja meiliaadress ja ametinimetus võiksid täituda automaatselt.

**Comment by RRisto** [comment]
Versioonis 2 seda funktisonaalsust pole. Küll aga on võimalik andmeid laadida üles ja alla excelist. Näiteks võib exceliga alla laadida juba kirjeldatud teenused, sinna lisada omaniku andmed ning täiendatud exceli üles laadida.
