### ISSUE TITLE
Kanalite loetelu täiendamine x-teega

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#6]
Teen ettepaneku täiendada kanalite loetelu x-tee kaudu osutamise kanaliga.
![kanalid](https://cloud.githubusercontent.com/assets/146800/10427004/6dc5284a-70ee-11e5-853c-45a3a736d2b2.PNG)

**Comment by RRisto** [comment]
Ma täpsustan üle, milliseid lõpptarbijale suunatud teenuseid saab tarbida x-tee kaudu? Mida kasutaja peaks selle tarbimiseks tegema?

**Comment by tormi** [comment]
> milliseid lõpptarbijale suunatud teenuseid saab tarbida x-tee kaudu?

Tegemist on nö siseteenusega, mida vajab ametnik/asutus. Vt. ka #16. Tarbimiseks tuleb juurdepääs taotleda ja min. MISP üles seada :)

**Comment by tormi** [comment]
Kanalina klassifitseerub ilmselt ka mõni muu (avaandmete) **API**, näiteks http://register.muinas.ee/public.php?menuID=open-data. 

Paraku tuleb siin lisaks rakendustele https://www.eesti.ee/, https://riha.eesti.ee/, https://www.riigiteenused.ee/ täiendavana pilti https://opendata.riik.ee/.

**Comment by tormi** [comment]
@RRisto , mis sellest ettepanekust on saanud? Me tahame SF-i rahadest x-tee teenust täiendada ja seetõttu ka rt.ee-s ära kirjeldada. Hetkel ei saa kanalina x-teed näidata.

**Comment by RRisto** [comment]
@tormi teeme nii, et sa kirjeldada teenuse rt-s ära ning paned loomisel seisundis (kanali valid siis suvalise). Me vaatame selle teenuse üle ning siis otsustame?

**Comment by tormi** [comment]
Ok, teeme nii.

**Comment by AnneliT** [comment]
Leian, et x-tee kanalina ei ole avalike teenuste lõpptarbija seisukohast kirjeldamisel asjakohane. Seda x-tee teenust te pakute lõpptarbijale ehk "kodanikule" ju mingis portaalis? Seega on kanal see portaal.

**Comment by tormi** [comment]
@AnneliT , kui otsida juba kirjeldatud riigiteenuste seast [fraasi x-tee](https://www.mkm.ee/et/teenuste-otsing?title-search=x-tee&field_t_kirjeldus_value=&sort_by=field_t_osutatud_teenuste_arv_value), siis on tulemustes nii RIA kui RIK x-tee teenused. Lisaks, ka ettevõtja võib x-tee kaudu KVR andmeid tarbida, seetõttu jääksin oma seisukoha juurde.

**Comment by RRisto** [comment]
kuna x-tee kanal pole kanal, mille kaudu lõpptarbija avalikku teenust tarbib, siis versioonis 2 seda kanali pole
