### ISSUE TITLE
Koodi litsentseerimine

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#7]
Hetkel puudub koodil litsents, teen ettepaneku see lisada koos kande #1 tegevustega. Kui veel pole kokku lepitud, teen ettepaneku litsentseerida [GPL v.2](https://github.com/drupal/drupal/blob/7.x/LICENSE.txt)-ga sarnaselt Drupalile, mille distro riigiteenused.ee on.

**Comment by RRisto** [comment]
Üks rumal küsimus, miks litsentsi üldse vaja on?

**Comment by RRisto** [comment]
hetkel pole litsentsi lisanud. hetkel ei tundu vajalik olevat: https://choosealicense.com/no-license/
