### ISSUE TITLE
riigiteenused.ee veateade

### ISSUE THREAD

**Issue by tormi** [MKM-ITAO/riigiteenused#9]
https://www.riigiteenused.ee/ suunab aadressile https://www.riigiteenused.ee/et/statistika/allasutus ja annab järgmise veateate: 

`Määratud faili temporary://fileHYbPAz polnud võimalik kopeerida, kuna sihtkataloog ei ole õigesti seadistatud. Seda võivad põhjustada väärad faili- kataloogiõigused. Täpsem info on süsteemi logis.
Määratud faili temporary://file0NJJKJ polnud võimalik kopeerida, kuna sihtkataloog ei ole õigesti seadistatud. Seda võivad põhjustada väärad faili- kataloogiõigused. Täpsem info on süsteemi logis.`

**Comment by Airir5** [comment]
Oleme teadlikud veateatest. Tegeleme sellega.

**Comment by tormi** [comment]
Proovisin uuesti, kirjeldatud suunamist ja veateadet enam ei esinenud.
